MICROWAVE_LINK_BUDGET_COLUMN_MAP = {
    "Vendor": "vendor",
    "Site name S1": "site_name_s1",
    "Site name S2": "site_name_s2",
    "State/ Provience": "state_province",
    "Township": "township",
    "Zone": "zone",
    "Region": "region",
    "Ring ID/Span Name": "ring_id_span_name",
    "Media Type (Fiber/ Microwave)": "media_type",
    "LinkID": "link_id",
    "Revise": "revise",
    "Site name S1 IP": "site_name_s1_ip",
    "Site name S2 IP": "site_name_s2_ip",
    "Site name S1 Port": "site_name_s1_port",
    "Site name S2 Port": "site_name_s2_port",
    "Class": "link_class",
    "Model": "model",
    "Status": "status",
    "Active": "active",
    "Protocol": "protocol",
    "Comment": "comment",
    "Status.1": "status_1",
    "Type": "type",
    "bandwidth": "bandwidth",
    "Planning Capacity": "planning_capacity",
    "Latitude S1": "latitude_s1",
    "Latitude S2": "latitude_s2",
    "Longitude S1": "longitude_s1",
    "Longitude S2": "longitude_s2",
    "True azimuth (°) S1": "true_azimuth_s1",
    "True azimuth (°) S2": "true_azimuth_s2",
    "Tower height (m) S1": "tower_height_s1",
    "Tower height (m) S2": "tower_height_s2",
    "TR Antenna model S1": "tr_antenna_model_s1",
    "TR Antenna model S2": "tr_antenna_model_s2",
    "TR Antenna diameter (m) S1": "tr_antenna_diameter_s1",
    "TR Antenna diameter (m) S2": "tr_antenna_diameter_s2",
    "TR Antenna height (m) S1": "tr_antenna_height_s1",
    "TR Antenna height (m) S2": "tr_antenna_height_s2",
    "Frequency (MHz)": "frequency_mhz",
    "Polarization": "polarization",
    "Path length (km)": "path_length_km",
    "Radio model S1": "radio_model_s1",
    "Radio model S2": "radio_model_s2",
    "#1 Design frequency S1": "design_frequency_1_s1",
    "#1 Design frequency S2": "design_frequency_1_s2",
    "#2 Design frequency S1": "design_frequency_2_s1",
    "#2 Design frequency S2": "design_frequency_2_s2",
    "#3 Design frequency S1": "design_frequency_3_s1",
    "#3 Design frequency S2": "design_frequency_3_s2",
    "#4 Design frequency S1": "design_frequency_4_s1",
    "#4 Design frequency S2": "design_frequency_4_s2",
    "TX power (dBm) S1": "tx_power_dbm_s1",
    "TX power (dBm) S2": "tx_power_dbm_s2",
    "RX threshold level (dBm) S1": "rx_threshold_level_dbm_s1",
    "RX threshold level (dBm) S2": "rx_threshold_level_dbm_s2",
    "Radio file name S1": "radio_file_name_s1",
    "Radio file name S2": "radio_file_name_s2",
    "Receive signal (dBm) S1": "receive_signal_dbm_s1",
    "Receive signal (dBm) S2": "receive_signal_dbm_s2",
    "Thermal fade margin (dB) S1": "thermal_fade_margin_db_s1",
    "Thermal fade margin (dB) S2": "thermal_fade_margin_db_s2",
    "Effective fade margin (dB) S1": "effective_fade_margin_db_s1",
    "Effective fade margin (dB) S2": "effective_fade_margin_db_s2",
    "Annual multipath availability (%) S1": "annual_multipath_availability_s1",
    "Annual multipath availability (%) S2": "annual_multipath_availability_s2",
    "Annual rain availability (%) S1": "annual_rain_availability_s1",
    "Annual rain availability (%) S2": "annual_rain_availability_s2",
    "#1 ATPC S1": "atpc_1_s1",
    "#1 ATPC S2": "atpc_1_s2",
}