export const siteConnectivityColumns = [
  { key: "sitea_id", label: "SiteA ID" },
  { key: "siteb_id", label: "SiteB ID" },
  { key: "link_id", label: "Link ID" },
  { key: "category_ne", label: "Category [NE]" },
  { key: "depth", label: "Depth" },
  { key: "dependency", label: "Dependency" },
  { key: "pop_site", label: "POP Site" },
  { key: "child_site_connectivity", label: "Child Site Connectivity" },
  { key: "child_site_name", label: "Child Site Name" },
  { key: "budget_vendor", label: "Vendor" },
  { key: "budget_site_name_s1", label: "Site Name S1" },
  { key: "budget_site_name_s2", label: "Site Name S2" },
  { key: "budget_revise", label: "Revise" },
  { key: "budget_protocol", label: "Protocol" },
  { key: "budget_status", label: "Status" },
  { key: "budget_model", label: "Model" },
  { key: "budget_bandwidth", label: "Bandwidth" },
  { key: "budget_site_name_s1_ip", label: "Site S1 IP" },
  { key: "budget_site_name_s2_ip", label: "Site S2 IP" },
];